var annotated_dup =
[
    [ "Captain", "namespace_captain.html", [
      [ "DMode", "namespace_captain_1_1_d_mode.html", [
        [ "AdjSpeed", "class_captain_1_1_d_mode_1_1_adj_speed.html", "class_captain_1_1_d_mode_1_1_adj_speed" ],
        [ "ApproachStation", "class_captain_1_1_d_mode_1_1_approach_station.html", "class_captain_1_1_d_mode_1_1_approach_station" ],
        [ "BCF", "class_captain_1_1_d_mode_1_1_b_c_f.html", "class_captain_1_1_d_mode_1_1_b_c_f" ],
        [ "BLC", "class_captain_1_1_d_mode_1_1_b_l_c.html", "class_captain_1_1_d_mode_1_1_b_l_c" ],
        [ "CCF", "class_captain_1_1_d_mode_1_1_c_c_f.html", "class_captain_1_1_d_mode_1_1_c_c_f" ],
        [ "CF", "class_captain_1_1_d_mode_1_1_c_f.html", "class_captain_1_1_d_mode_1_1_c_f" ],
        [ "CV", "class_captain_1_1_d_mode_1_1_c_v.html", "class_captain_1_1_d_mode_1_1_c_v" ],
        [ "DLC", "class_captain_1_1_d_mode_1_1_d_l_c.html", "class_captain_1_1_d_mode_1_1_d_l_c" ],
        [ "DriveModel", "class_captain_1_1_d_mode_1_1_drive_model.html", "class_captain_1_1_d_mode_1_1_drive_model" ],
        [ "ELC", "class_captain_1_1_d_mode_1_1_e_l_c.html", "class_captain_1_1_d_mode_1_1_e_l_c" ],
        [ "IAutomaticallyDeactivated", "class_captain_1_1_d_mode_1_1_i_automatically_deactivated.html", "class_captain_1_1_d_mode_1_1_i_automatically_deactivated" ],
        [ "IMultipleVehicleTrackable", "class_captain_1_1_d_mode_1_1_i_multiple_vehicle_trackable.html", "class_captain_1_1_d_mode_1_1_i_multiple_vehicle_trackable" ],
        [ "IntersectionCF", "class_captain_1_1_d_mode_1_1_intersection_c_f.html", "class_captain_1_1_d_mode_1_1_intersection_c_f" ],
        [ "MCF", "class_captain_1_1_d_mode_1_1_m_c_f.html", "class_captain_1_1_d_mode_1_1_m_c_f" ],
        [ "Stay", "class_captain_1_1_d_mode_1_1_stay.html", "class_captain_1_1_d_mode_1_1_stay" ]
      ] ],
      [ "Node", "namespace_captain_1_1_node.html", [
        [ "EnhancedMicroLink", "class_captain_1_1_node_1_1_enhanced_micro_link.html", "class_captain_1_1_node_1_1_enhanced_micro_link" ],
        [ "ILinkable", "struct_captain_1_1_node_1_1_i_linkable.html", "struct_captain_1_1_node_1_1_i_linkable" ],
        [ "IntersectionMicroLink", "class_captain_1_1_node_1_1_intersection_micro_link.html", "class_captain_1_1_node_1_1_intersection_micro_link" ],
        [ "IVehicleContainableUnit", "struct_captain_1_1_node_1_1_i_vehicle_containable_unit.html", "struct_captain_1_1_node_1_1_i_vehicle_containable_unit" ],
        [ "MesoLink", "class_captain_1_1_node_1_1_meso_link.html", "class_captain_1_1_node_1_1_meso_link" ],
        [ "MesoUnit", "class_captain_1_1_node_1_1_meso_unit.html", "class_captain_1_1_node_1_1_meso_unit" ],
        [ "MicroLane", "class_captain_1_1_node_1_1_micro_lane.html", "class_captain_1_1_node_1_1_micro_lane" ],
        [ "MicroLink", "class_captain_1_1_node_1_1_micro_link.html", "class_captain_1_1_node_1_1_micro_link" ],
        [ "SinkUnit", "class_captain_1_1_node_1_1_sink_unit.html", "class_captain_1_1_node_1_1_sink_unit" ],
        [ "SourceUnit", "class_captain_1_1_node_1_1_source_unit.html", "class_captain_1_1_node_1_1_source_unit" ],
        [ "Station", "class_captain_1_1_node_1_1_station.html", "class_captain_1_1_node_1_1_station" ],
        [ "UniformIntersectionLink", "class_captain_1_1_node_1_1_uniform_intersection_link.html", "class_captain_1_1_node_1_1_uniform_intersection_link" ],
        [ "UniformLink", "class_captain_1_1_node_1_1_uniform_link.html", "class_captain_1_1_node_1_1_uniform_link" ],
        [ "UnitConnectionInfo", "struct_captain_1_1_node_1_1_unit_connection_info.html", "struct_captain_1_1_node_1_1_unit_connection_info" ]
      ] ],
      [ "Util", "namespace_captain_1_1_util.html", [
        [ "EventRecorder", "class_captain_1_1_util_1_1_event_recorder.html", "class_captain_1_1_util_1_1_event_recorder" ],
        [ "EventRecorderContainer", "struct_captain_1_1_util_1_1_event_recorder_container.html", "struct_captain_1_1_util_1_1_event_recorder_container" ],
        [ "JsonReader", "class_captain_1_1_util_1_1_json_reader.html", "class_captain_1_1_util_1_1_json_reader" ],
        [ "JsonWriter", "class_captain_1_1_util_1_1_json_writer.html", "class_captain_1_1_util_1_1_json_writer" ],
        [ "VehicleQueue", "class_captain_1_1_util_1_1_vehicle_queue.html", "class_captain_1_1_util_1_1_vehicle_queue" ],
        [ "XmlWriter", "class_captain_1_1_util_1_1_xml_writer.html", "class_captain_1_1_util_1_1_xml_writer" ]
      ] ],
      [ "BasicMesoModel", "struct_captain_1_1_basic_meso_model.html", "struct_captain_1_1_basic_meso_model" ],
      [ "ConcurrentQueue", "class_captain_1_1_concurrent_queue.html", "class_captain_1_1_concurrent_queue" ],
      [ "DriveModeDescriptor", "class_captain_1_1_drive_mode_descriptor.html", "class_captain_1_1_drive_mode_descriptor" ],
      [ "Engine", "class_captain_1_1_engine.html", "class_captain_1_1_engine" ],
      [ "EnumConstRefHolder", "struct_captain_1_1_enum_const_ref_holder.html", "struct_captain_1_1_enum_const_ref_holder" ],
      [ "EnumRefHolder", "struct_captain_1_1_enum_ref_holder.html", "struct_captain_1_1_enum_ref_holder" ],
      [ "EnumStrings", "struct_captain_1_1_enum_strings.html", null ],
      [ "ExponentialDistribution", "class_captain_1_1_exponential_distribution.html", "class_captain_1_1_exponential_distribution" ],
      [ "FileManager", "class_captain_1_1_file_manager.html", "class_captain_1_1_file_manager" ],
      [ "IEventRecordable", "struct_captain_1_1_i_event_recordable.html", "struct_captain_1_1_i_event_recordable" ],
      [ "Intersection", "class_captain_1_1_intersection.html", "class_captain_1_1_intersection" ],
      [ "IVehicleQueue", "class_captain_1_1_i_vehicle_queue.html", "class_captain_1_1_i_vehicle_queue" ],
      [ "LaneRecordInfo", "struct_captain_1_1_lane_record_info.html", "struct_captain_1_1_lane_record_info" ],
      [ "LinkLanePair", "struct_captain_1_1_link_lane_pair.html", "struct_captain_1_1_link_lane_pair" ],
      [ "MesoComputationModel", "struct_captain_1_1_meso_computation_model.html", "struct_captain_1_1_meso_computation_model" ],
      [ "MesoLinkInfo", "struct_captain_1_1_meso_link_info.html", "struct_captain_1_1_meso_link_info" ],
      [ "Message", "struct_captain_1_1_message.html", "struct_captain_1_1_message" ],
      [ "MicroLinkEventInfo", "struct_captain_1_1_micro_link_event_info.html", "struct_captain_1_1_micro_link_event_info" ],
      [ "microLinkEventInfoCompare", "struct_captain_1_1micro_link_event_info_compare.html", "struct_captain_1_1micro_link_event_info_compare" ],
      [ "MicroLinkInfo", "struct_captain_1_1_micro_link_info.html", "struct_captain_1_1_micro_link_info" ],
      [ "NormalDistribution", "class_captain_1_1_normal_distribution.html", "class_captain_1_1_normal_distribution" ],
      [ "pair_hash", "struct_captain_1_1pair__hash.html", "struct_captain_1_1pair__hash" ],
      [ "Passenger", "class_captain_1_1_passenger.html", "class_captain_1_1_passenger" ],
      [ "PassengerPath", "struct_captain_1_1_passenger_path.html", "struct_captain_1_1_passenger_path" ],
      [ "PathIdentifier", "struct_captain_1_1_path_identifier.html", "struct_captain_1_1_path_identifier" ],
      [ "PoissonDistribution", "class_captain_1_1_poisson_distribution.html", "class_captain_1_1_poisson_distribution" ],
      [ "Position", "struct_captain_1_1_position.html", "struct_captain_1_1_position" ],
      [ "RandomDistribution", "class_captain_1_1_random_distribution.html", "class_captain_1_1_random_distribution" ],
      [ "RandomEngine", "class_captain_1_1_random_engine.html", "class_captain_1_1_random_engine" ],
      [ "Route", "struct_captain_1_1_route.html", "struct_captain_1_1_route" ],
      [ "SegmentInfo", "struct_captain_1_1_segment_info.html", "struct_captain_1_1_segment_info" ],
      [ "SharedObjectInfo", "struct_captain_1_1_shared_object_info.html", "struct_captain_1_1_shared_object_info" ],
      [ "SharedPtr", "class_captain_1_1_shared_ptr.html", "class_captain_1_1_shared_ptr" ],
      [ "SharedSpinlock", "class_captain_1_1_shared_spinlock.html", null ],
      [ "SimpleUnitInfo", "struct_captain_1_1_simple_unit_info.html", "struct_captain_1_1_simple_unit_info" ],
      [ "SimulationRecordInfo", "struct_captain_1_1_simulation_record_info.html", "struct_captain_1_1_simulation_record_info" ],
      [ "SinkRecordInfo", "struct_captain_1_1_sink_record_info.html", "struct_captain_1_1_sink_record_info" ],
      [ "SpinLock", "class_captain_1_1_spin_lock.html", "class_captain_1_1_spin_lock" ],
      [ "SpinLockQueue", "class_captain_1_1_spin_lock_queue.html", "class_captain_1_1_spin_lock_queue" ],
      [ "SpinLockVehicleQueue", "class_captain_1_1_spin_lock_vehicle_queue.html", "class_captain_1_1_spin_lock_vehicle_queue" ],
      [ "StationRecordInfo", "struct_captain_1_1_station_record_info.html", "struct_captain_1_1_station_record_info" ],
      [ "tuple_hash", "struct_captain_1_1tuple__hash.html", "struct_captain_1_1tuple__hash" ],
      [ "UniformDistribution", "class_captain_1_1_uniform_distribution.html", "class_captain_1_1_uniform_distribution" ],
      [ "UnitConnectionDescriptor", "struct_captain_1_1_unit_connection_descriptor.html", "struct_captain_1_1_unit_connection_descriptor" ],
      [ "UnitIdentifier", "struct_captain_1_1_unit_identifier.html", "struct_captain_1_1_unit_identifier" ],
      [ "UnitPosition", "struct_captain_1_1_unit_position.html", "struct_captain_1_1_unit_position" ],
      [ "V2X", "class_captain_1_1_v2_x.html", "class_captain_1_1_v2_x" ],
      [ "Vehicle", "class_captain_1_1_vehicle.html", "class_captain_1_1_vehicle" ],
      [ "VehicleContainer", "class_captain_1_1_vehicle_container.html", null ],
      [ "VehicleDescriptor", "struct_captain_1_1_vehicle_descriptor.html", "struct_captain_1_1_vehicle_descriptor" ],
      [ "VehicleInfo", "struct_captain_1_1_vehicle_info.html", "struct_captain_1_1_vehicle_info" ],
      [ "VehiclePath", "struct_captain_1_1_vehicle_path.html", "struct_captain_1_1_vehicle_path" ],
      [ "VehicleRecordInfo", "struct_captain_1_1_vehicle_record_info.html", "struct_captain_1_1_vehicle_record_info" ],
      [ "VehicleReservationInfo", "class_captain_1_1_vehicle_reservation_info.html", "class_captain_1_1_vehicle_reservation_info" ],
      [ "VehicleState", "struct_captain_1_1_vehicle_state.html", "struct_captain_1_1_vehicle_state" ],
      [ "WeakPtr", "class_captain_1_1_weak_ptr.html", "class_captain_1_1_weak_ptr" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Captain::UnitIdentifier >", "structstd_1_1hash_3_01_captain_1_1_unit_identifier_01_4.html", "structstd_1_1hash_3_01_captain_1_1_unit_identifier_01_4" ]
    ] ],
    [ "AgentsArr", "class_agents_arr.html", "class_agents_arr" ],
    [ "AgentTypesArr", "class_agent_types_arr.html", "class_agent_types_arr" ],
    [ "connection", "classconnection.html", "classconnection" ],
    [ "Demand", "class_demand.html", "class_demand" ],
    [ "DemandInfo", "class_demand_info.html", "class_demand_info" ],
    [ "EventArr", "class_event_arr.html", "class_event_arr" ],
    [ "InputAgents", "class_input_agents.html", "class_input_agents" ],
    [ "InputAgentTypes", "class_input_agent_types.html", "class_input_agent_types" ],
    [ "InputCell", "class_input_cell.html", "class_input_cell" ],
    [ "InputDistribution", "class_input_distribution.html", "class_input_distribution" ],
    [ "InputEvent", "class_input_event.html", "class_input_event" ],
    [ "InputLane", "class_input_lane.html", "class_input_lane" ],
    [ "InputLink", "class_input_link.html", "class_input_link" ],
    [ "InputMessage", "class_input_message.html", "class_input_message" ],
    [ "InputPax", "class_input_pax.html", "class_input_pax" ],
    [ "InputSegment", "class_input_segment.html", "class_input_segment" ],
    [ "InputStation", "class_input_station.html", "class_input_station" ],
    [ "IntersectionNode", "class_intersection_node.html", "class_intersection_node" ],
    [ "intersectionPhase", "classintersection_phase.html", "classintersection_phase" ],
    [ "LinkArr", "class_link_arr.html", "class_link_arr" ],
    [ "MessageArr", "class_message_arr.html", "class_message_arr" ],
    [ "MetaData", "class_meta_data.html", "class_meta_data" ],
    [ "Mode", "class_mode.html", "class_mode" ],
    [ "ModeArr", "class_mode_arr.html", "class_mode_arr" ],
    [ "NodeArr", "class_node_arr.html", "class_node_arr" ],
    [ "ODMatrix", "class_o_d_matrix.html", "class_o_d_matrix" ],
    [ "ParamArr", "class_param_arr.html", "class_param_arr" ],
    [ "PaxArr", "class_pax_arr.html", "class_pax_arr" ],
    [ "port", "classport.html", "classport" ],
    [ "Scenario", "class_scenario.html", "class_scenario" ],
    [ "StationArr", "class_station_arr.html", "class_station_arr" ]
];